filename=main

tex:
	pdflatex main.tex
	pdflatex main.tex
	bibtex main
	pdflatex main.tex

clean:
	rm -f ${filename}.aux
	rm -f ${filename}.bbl
	rm -f ${filename}.blg
	rm -f ${filename}.log
	rm -f ${filename}.out



